"""progress

Revision ID: 20ec558d56d9
Revises: 2b333159a446
Create Date: 2023-09-03 16:41:57.830214

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20ec558d56d9"
down_revision: Union[str, None] = "2b333159a446"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("progression", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"], ["target.id"], name=op.f("fk_progress_target_id_target")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_progress_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress")),
        sa.UniqueConstraint("id", name=op.f("uq_progress_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("progress")
    # ### end Alembic commands ###
