"""empty message

Revision ID: 2486e1d5cef6
Revises: 20ec558d56d9
Create Date: 2023-09-03 21:46:06.590256

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2486e1d5cef6"
down_revision: Union[str, None] = "20ec558d56d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("progress")
    op.add_column(
        "target", sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target", "progress")
    op.create_table(
        "progress",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("progression", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("target_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["target_id"], ["target.id"], name="fk_progress_target_id_target"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_progress_user_id_user"),
        sa.PrimaryKeyConstraint("id", name="pk_progress"),
    )
    # ### end Alembic commands ###
