"""test

Revision ID: 2b333159a446
Revises: 5fd5f71af7ef
Create Date: 2023-08-08 17:11:31.269114

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b333159a446"
down_revision: Union[str, None] = "5fd5f71af7ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_goal_id"), "goal", ["id"])
    op.create_unique_constraint(op.f("uq_target_id"), "target", ["id"])
    op.create_unique_constraint(op.f("uq_user_id"), "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_id"), "user", type_="unique")
    op.drop_constraint(op.f("uq_target_id"), "target", type_="unique")
    op.drop_constraint(op.f("uq_goal_id"), "goal", type_="unique")
    # ### end Alembic commands ###
